SHELL := /bin/bash

# -----------------------------------------------------------------------------
# Common commands
# -----------------------------------------------------------------------------
# Compile only:
#   make vcs_build
#
# Run one testcase (waveform is generated by default):
#   make vcs_run TEST=dma_apb_copy_test SEED=1
#
# Run the complete regression (one command, waveform disabled):
#   make regression
#
# Open the latest single-run waveform with Verdi:
#   verdi -dbdir simv.daidir -ssf waveform.fsdb &
#
# Open accumulated coverage with Verdi:
#   verdi -cov -covdir simv.vdb &
#
# Remove all generated files:
#   make clean

VCS        ?= vcs
SIMV       ?= simv
UVM_HOME   ?= /mtklib/soft/verif/Methodology/UVM/uvm/uvm-1.1d/src
NOVAS_HOME ?= $(VERDI_HOME)

TEST       ?= dma_apb_smoke_test
SEED       ?= 1
VERBOSITY  ?= UVM_LOW
RANDOM_OPS ?= 40
WAVE       ?= 1
LOG        ?= sim.log

VCS_FLAGS ?= -full64 -licqueue -sverilog -timescale=1ns/1ps \
             -debug_access+all -kdb +memcbk \
             +define+UVM_OBJECT_MUST_HAVE_CONSTRUCTOR \
             +define+ENABLE_FSDB +incdir+$(UVM_HOME)

FSDB_FLAGS ?= -P $(NOVAS_HOME)/share/PLI/VCS/LINUX64/novas.tab \
                $(NOVAS_HOME)/share/PLI/VCS/LINUX64/pli.a

CM_FLAGS ?= -cm line+cond+tgl+fsm+branch+assert

DIRECTED_TESTS ?= dma_apb_smoke_test \
                  dma_apb_register_direct_test \
                  dma_apb_init_test \
                  dma_apb_copy_test \
                  dma_apb_interrupt_test \
                  dma_apb_target_wait_test \
                  dma_apb_busy_test \
                  dma_apb_reset_test

RANDOM_SEEDS ?= 1 2 3 4 5

SOURCE_FILES := top.sv test.sv apb_device.v \
                $(wildcard src/*.sv) \
                $(wildcard sequences/*.sv) \
                $(wildcard tests/*.sv) \
                $(wildcard apb_device_src/*.sv)

ifeq ($(WAVE),1)
WAVE_ARGS := +DUMP_FSDB +FSDB_FILE=waveform.fsdb
else
WAVE_ARGS :=
endif

.PHONY: all vcs_build vcs_run regression clean check_env

all: vcs_run

check_env:
	@test -f "$(UVM_HOME)/uvm.sv" || { \
		echo "ERROR: $(UVM_HOME)/uvm.sv not found"; exit 2; }
	@test -f "$(UVM_HOME)/dpi/uvm_dpi.cc" || { \
		echo "ERROR: $(UVM_HOME)/dpi/uvm_dpi.cc not found"; exit 2; }
	@test -n "$(NOVAS_HOME)" || { \
		echo "ERROR: NOVAS_HOME or VERDI_HOME is not set"; exit 2; }

vcs_build: $(SIMV)

$(SIMV): $(SOURCE_FILES) filelist.f Makefile | check_env
	$(VCS) $(VCS_FLAGS) $(FSDB_FLAGS) $(CM_FLAGS) \
		$(UVM_HOME)/uvm.sv $(UVM_HOME)/dpi/uvm_dpi.cc \
		-CFLAGS -DVCS -f filelist.f -cm_dir simv.vdb \
		-o $(SIMV) -l compile.log

vcs_run: $(SIMV)
	@./$(SIMV) \
		+UVM_TESTNAME=$(TEST) \
		+UVM_VERBOSITY=$(VERBOSITY) \
		+UVM_MAX_QUIT_COUNT=1,NO \
		+ntb_random_seed=$(SEED) \
		+DMA_RANDOM_OPS=$(RANDOM_OPS) \
		+vcs+lic+wait $(WAVE_ARGS) \
		$(CM_FLAGS) -cm_dir simv.vdb -cm_name $(TEST)_$(SEED) \
		-l $(LOG); status=$$?; \
	./scripts/check_run.sh "$(LOG)" $$status

# A fresh regression is built automatically. Directed tests run once with
# seed 1; the random test runs with every seed in RANDOM_SEEDS. All runs write
# into simv.vdb using a unique -cm_name, so Verdi can display accumulated
# coverage directly without a separate merge command.
regression:
	@$(MAKE) --no-print-directory clean
	@$(MAKE) --no-print-directory vcs_build
	@mkdir -p regression_logs
	@set -e; \
	for test_name in $(DIRECTED_TESTS); do \
		echo "[REGRESSION] TEST=$$test_name SEED=1"; \
		$(MAKE) --no-print-directory vcs_run \
			TEST=$$test_name SEED=1 WAVE=0 \
			LOG=regression_logs/$${test_name}_1.log; \
	done; \
	for random_seed in $(RANDOM_SEEDS); do \
		echo "[REGRESSION] TEST=dma_apb_random_test SEED=$$random_seed"; \
		$(MAKE) --no-print-directory vcs_run \
			TEST=dma_apb_random_test SEED=$$random_seed WAVE=0 \
			LOG=regression_logs/dma_apb_random_test_$${random_seed}.log; \
	done
	@echo "Regression complete. Open coverage with:"
	@echo "  verdi -cov -covdir simv.vdb &"

clean:
	rm -rf csrc simv simv.daidir simv.vdb \
		ucli.key vc_hdrs.h DVEfiles verdiLog novas.conf novas_dump.log AN.DB \
		compile.log sim.log regression_logs waveform.fsdb \
		dma_read.txt dma_write.txt
